humbug/humbug

composer.json
refs : 
- https://github.com/zendframework/zf2/commit/e58c6cdbf50dd06b71e76a413fb870c95ab22bf5
- https://github.com/symfony/symfony/pull/5627
=> Optimize autoload prefix in composer.json

src/Humbug/Adapter/Phpunit.php
Err, needs work but putting it up here in case someone runs in to it
=> Look for the bootstrap file relative to the config file

src/Humbug/Adapter/Phpunit/XmlConfiguration.php
I'm trying to get humbug to work on the Drupal code base. Drupal uses wildcards in its `phpunit.xml.dist` to include tests that are written for modules:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="tests/bootstrap.php" colors="true">
<testsuites>
<testsuite name="Drupal Unit Test Suite">
<directory>./modules/*/tests</directory>
<directory>../sites/*/modules</directory>
</testsuite>
</testsuites>
</phpunit>
```
This branch allows these wildcards to be used. It will substitute these paths with a range of new paths that match the wildcard pattern.
I've had to implement it using a for loop instead of a regular foreach because DOMDocument does not handle loops well when the items in the loop are being manipulated. It's also not possible to remove elements inside the loop, …
=> Allow to use wildcards in testsuite paths.

.travis.yml
=> Added Travis Information

tests/Humbug/Test/Mutator/ReturnValue/FunctionCall.php
New Unit Test
padraic/humbug#51
=> Added Test for FunctionCall

src/Humbug/Mutator/ReturnValue/Integer.php, tests/Humbug/Test/Mutator/ReturnValue/IntegerTest.php
=> padraic/humbug Added Test for ReturnInteger and Simplified a little

README.md
=> Remove the reference to Runkit in the readme

tests/Humbug/Test/Adapter/Phpunit/JobTest.php
as Job.php in Utility moved to Adapter/Phpunit. travis should be green now ;)
=> move Test/Utility/JobTest.php to Test/Adapter/Phpunit/JobTest.php

src/Command/Humbug.php, src/Report/Text.php, tests/Report/TextTest.php
Preparing text report moved do saparate class. Its now more testable.
=> Text report generation refactoring

bin/humbug
=> Unknown configure class fix

README.md, bin/humbug, src/Command/Configure.php, src/Command/Humbug.php, tests/Command/ConfigureTest.php
This is first part of #126.
Running this is possible with `humbug configure` via CLI.
To merge it requires: 
* upgrade with texts and colors displayed to user - I hope to get some help with texts as I`m good with user experience
* update of README.md
* optional is to move tests to behat scenarios. As it would increase readability of those tests. If it is not in this PR I`ll move it to second part of #126
Please don`t merge before texts are OK.
=> Configure command

src/Adapter/Phpunit/XmlConfiguration/ObjectVisitor.php, src/Command/Humbug.php, src/Renderer/Text.php, src/Utility/CoverageData.php
@padraic requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/padraic/humbug/
=> Scrutinizer Auto-Fixes

src/Config.php, tests/ConfigTest.php
=> Create logging directory

src/TestSuite/Mutant/Observers/SpinnerObserver.php
It was annoying me that StyleCI was reporting as failed because of some whitespace, so I had to fix it.
=> Fix StyleCI

README.md
Small but important documentation corrections.
=> Corrected documentation for Escaped Mutations and Fatal Errors.

composer.json
To work with global installations of PHPUnit 5+
=> Allow for newer phpunit versions

src/Report/Text.php, src/TestSuite/Mutant/Collector.php, src/TestSuite/Mutant/Observers/JsonLoggingObserver.php, src/TestSuite/Mutant/Observers/TextLoggingObserver.php
=> Added reporting of uncovered lines to text and json output

bootstrap.php, features/bootstrap/FeatureContext.php
=> Support PHP_CodeCoverage 4.0 and PHPUnit 5.4

composer.json
This PR allows Symfony 3.x Components to be used.
=> Allow Symfony 3.x Components

README.md
=> Update Travis CI and Scrutinizer badges in readme

src/Adapter/Phpunit/Job.php
=> Load Humbug's bootstrap by loading the PHAR file with an alias
