humbug/humbug

tests/Humbug/Test/Adapter/PhpunitTest.php

Running Humbug's unit tests would fail with
PHP Fatal error:  Cannot use object of type Symfony\Component\Process\PhpProcess as array in /home/vagrant/humbug/tests/Humbug/Test/Adapter/PhpunitTest.php on line 60
so I guess explicitly calling the `process->run()` is needed in tests. Plus the Phpunit adapter returns a process, does not call it https://github.com/padraic/humbug/blob/master/src/Humbug/Adapter/Phpunit.php#L126

run processes so we can get the output

---

src/Humbug/Command/Humbug.php
src/Humbug/Renderer/Text.php

Don't use flaky output parsing:
- Stderr may contain output from external commands while bootstrapping
with merely warnings
- Stdout parsing is too flaky if there are skipped tests.

Check exit code for phpunit failure

---

src/Humbug/Adapter/Phpunit.php

This fixes errors when exec etc. is used for example in test
bootstrapping that rely on ENV variables.
This only works if E is included in the ini setting 'variable_order'.
This probably should be fixed in PhpProcess to allow env forwarding by
setting the parameter $env to null.

Pass through ENV variables

---

src/Humbug/Adapter/Phpunit.php

If the phpunit.xml file is incorrectly/differently configured, `$suite1` is  going to be null.
If there is no `<testsuites>` tag around the `<testsuite>` tag in the phpunit.xml file, the xpath query will find nothing.

check if suite is a DOMElement

---

src/Humbug/Adapter/Phpunit.php

Humbug reports to work on PHP 5.4, but method return values in `empty` is only supported in PHP >= 5.5

Method return value in empty only work in PHP 5.5

---

src/Humbug/Adapter/Phpunit.php

Check if files exist using `glob` instead of `file_exists`, so it can work with E.G `../src/*/*Bundle/Tests` in the phpunit.xml config

Check if files exist using glob

---

src/Humbug/Adapter/Phpunit/XmlConfiguration.php

When humbug is running with chdir we need to add this dir to every node value of phpunit.xml since they have relative paths. Otherwise we have 
[Humbug\Exception\RuntimeException]
Unable to locate file specified in testsuites: Events/Test

Full path for glob when running with chdir

---

composer.json

Dependency should have upper bounds and your version constraint on padraic/phpunit-accelerator was incorrect.

Composer fixes

---

src/Humbug/Mutator/Arithmetic/Addition.php
tests/Humbug/Test/MutableTest.php
tests/Humbug/Test/_files/root/base2/library/array1.php

With this change. Humbug avoids creating a mutation when it encounters something like:
```php
['foo' => 'x'] + ['bar' => 'x']
```
Which created an exception when mutated to:
```php
['foo' => 'x'] - ['bar' => 'x']
```

Avoid creating mutations on array union

---

src/Humbug/Adapter/Phpunit/XmlConfiguration.php

I am using the following configuration:
```
{
"timeout": 10, 
"source": {
"directories": [
"." 
],  
"excludes": [
"humbug",
"vendor"
]   
},  
"logs": {
"text": "humbuglog.txt"
}   
}
```
When I run humbug it throws an exception when it tries to resolve a path with a wildcard. This is because it is using `file_exists()` which cannot handle paths with wildcards:
```
[Humbug\Exception\InvalidArgumentException]                                           
Could not find file ./modules/*/tests working from /home/pieter/drupal/core
```
This can be solved by falling back to using `glob()` to check if any files exist that match the wildcard path.

Allow to return the real path of folders containing wildcards.

---

src/Humbug/Utility/CoverageData.php

When the coverage file is missing the exception that is thrown in `CoverageData::__construct()` uses the output from `realpath()` to create the exception message. However if the file is missing `realpath()` returns `FALSE ` so the filename appears empty.

Fix assertion message to show the missing file.

---

src/Humbug/Utility/Job.php

Use single quotes instead of double quotes to prevent PHP from interpreting escape sequences. This fixes #46.

Use single quotes.

---

src/Humbug/Adapter/Phpunit.php

This works on my machine. I don't know if it breaks on Windows.

Prefix PHP command line with 'exec', resolves #63

---

composer.json

PSR-4 allows for shallower directory structures, which is (intentionally) not included in this PR.

Switch to PSR-4 autoloading

---

src/Humbug/Command/Humbug.php

Returning the exit code to the Symfony Application rather than exiting directly in the command gives more flexibility (you would be able to run tests for your command for instance, while it would be a pain when using ``exit``)

Change the way to return a failure exit code in the command

---

src/Utility/CoverageData.php

This should make it possible to (finally) run Humbug on Windows. Currently it manages to detect line coverage just fine after the initial test run, but while running the actual mutation testing it marks every test with a S (uncovered).
I managed to track the issue down to the `coverage.humbug.[hash].cache` file, more specifically the name of the cache file. On Windows all the file paths' backslashes are escaped in the coverage report (coverage.humbug.php), so `C:\Path\To\My\File.php` would be `C:\\Path\\To\\My\\File.php` and this is the path being md5'd for the filename of the cache. To retrieve this cache file later the method `loadCoverageFor()` is called with a file path, this path however isn't escaped so the method would end up with a different hash and thus can't find the cache …

Strip slashes to fix Windows issue.

---

src/Adapter/AdapterAbstract.php
src/Adapter/Locator.php
src/Adapter/Phpunit/XmlConfiguration.php
src/Adapter/Phpunit/XmlConfiguration/ReplaceWildcardVisitor.php
src/Adapter/Phpunit/XmlConfigurationBuilder.php
tests/Adapter/LocatorTest.php
tests/Adapter/Phpunit/XmlConfiguration/ReplaceWildcardVisitorTest.php
tests/Adapter/Phpunit/XmlConfigurationBuilderTest.php
tests/Adapter/Phpunit/XmlConfigurationTest.php
tests/Adapter/PhpunitTest.php
tests/Adapter/_files/regression/wildcard-dirs/phpunit.xml
tests/Adapter/_files/regression/wildcard-dirs/second-suite/Tests/SecondTest.php
tests/Adapter/_files/regression/wildcard-dirs/suite-first/Tests/FirstTest.php

After #104 replacement for wildcard directories in phpunit.xml disapeard.
It fixes this issue. And it will fix #110 with 90% sure.

XmlConfiguration fixed for wildcards in directoies

---

src/Adapter/Phpunit.php
tests/Adapter/PhpunitTest.php

Main cause of #110 was that there was a problem with searching for testsuites ditecories to relative path given with chrdir.

Humbug should work with relative chdir

---

src/Mutant.php

Changes the path of the file affected by a mutant in the JSON log file to be relative to the root of the project, as it makes it more complicated to parse the log on a different machine than the one where the mutation tests were run.
This P/R does not affect text logs.

Return relative file path in Mutant::toArray

---

bin/humbug
src/Command/Humbug.php
src/Console/Application.php

As self-update was next command in humbug it may me executed as command. Subcommand approach does not fit here IMO.
Running `humbug` still works by setting default command in bin/humbug if it was not set.

Prepare humbug to have more than 1 command in it

---

src/Mutator/Arithmetic/BitwiseAnd.php
src/Mutator/MutatorAbstract.php
tests/Mutator/Arithmetic/BitwiseAndTest.php

Correctly detect reference operator when wrapped in whitespace

---

tests/Adapter/Phpunit/XmlConfigurationTest.php
tests/GeneratorTest.php
tests/MutantTest.php

When running `phpunit --coverage-text` several tests are failing on Windows due to directory separator  issues. This PR fixes this by replacing the hard-coded slashes with DIRECTORY_SEPARATOR in the tests.

fixes failing tests due to DIRECTORY_SEPARATOR issues

---

src/Command/Humbug.php

In my work-flow, each analysis tool has it's own configuration file (e.g. `phpunit.xml(.dist)`) which I use to determine what should be analysed and how. Logging can also be configured in these files (as is the case with humbug), however I prefer to use command line options.
e.g.
PHPUnit has `--log-json path/to/logfile.json`
PHP_CodeSniffer has `--report-json=path/to/logfile.json`
These command line options allow the tools to perform their analysis consistently when used by external systems, while allowing each individual's logging needs to be satisfied.
This PR adds two new command line options:
`--log-json=path/to/logfile.json` and `--log-text=path/to/logfile.txt`
Log files can still be configured in the `humbug.json(.dist)` file, however the command line options (if present) will take …

Implemented command line configuration of log files

---

src/Adapter/Phpunit/Listeners/JsonLoggingTimeCollectorListener.php
src/Adapter/Phpunit/Listeners/TestSuiteFilterListener.php
src/Adapter/Phpunit/XmlConfigurationBuilder.php
tests/Adapter/Phpunit/XmlConfigurationBuilderTest.php

This PR fixes issue #158 (and its duplicate #161) by using listeners that do not have an object as its dependencies.
Note that the original bug is due to  sebastianbergmann/phpunit#1873, this PR simply circumvents the bug.
~~It should be save to merge this PR~~ however I have not yet added tests for the `TestSuiteFilterListener` and `JsonLoggingTimeCollectorListener`. I'm also not sure about the naming I've used, so any feedback is welcome.
Edit: I forgot to check Behat, I'm working on fixing the tests.

Fix phpunit listener

---

bin/humbug
src/Command/Stats.php
src/Log/JsonLogParser.php

I've used this code in my projects and think it can be useful in humbug itself.
New command added, so you can call:
> bin/humbug stats ../my-project/humbuglog.json ../my-project/list-of-classes.txt --skip-killed=yes [-vvv]
and get stats parsed from humbuglog.json
CLI reference:
humbug stats [humbuglog.json location] [class list location] [--skip-killed=yes] [-vvv]
* humbuglog.json location,  defaults to ./humbuglog.json
* class list location is a path of text file, containing full class names, one per line. 
only this files-related stats would be shown
* --skip-killed=yes is used to completely skip output of "killed" section
* various verbosity levels define amount of info to be displayed:
* by default, there's one line per class with amount of mutants killed/escaped/errored/timed out …

Added simple CLI interface to check humbuglog.json stats

---

.travis.yml

This prevents me from testing branches on my fork. With Humbug being an organisation, we can all make PRs from our forks, so no duplicated builds will be created. Anyway, it can be configured in Travis project settings (if not already done in `.travis.yml` as it is now).

Run Travis builds for all branches

---

features/version.feature
src/Console/Application.php

Part of #219, should solve failing builds on PHP 5.5.

Unify version displaying format

---

features/bootstrap/FilesystemContext.php

Fixes #219.
Dirty hack to make Humbug use `phpunit` downloaded using Composer.

Make Behat tests up and running

---

src/Adapter/Phpunit/Process/PhpunitExecutableFinder.php
src/Config.php
tests/Adapter/Phpunit/Process/PhpunitExecutableFinderTest.php

This is my attempt to implement the feature requested by the user domnikl and me in Issue #154.
Behaviour of the application remains unchanged as long as the user doesn't include the location of a phpunit.phar in the configfile. If he does, path and name of the provided executable will be passed to the ExecutableFinder.
``` json
{
"source": {
"directories": [
"src"
]
},
...
"phpunit": {
"phar": "/absolute/path/to/phpunit-4.8.3.phar"
}
}
```
If this pull request somehow doesn't measure up to your expectations for a proper PR or you don't want to implement the feature I would be glad to hear from you.

Support for optionally configuring phpunit executable

---

README.md
bin/humbug
bootstrap.php

Fix for https://github.com/padraic/humbug/issues/178
So far it runs fine for `./bin/humbug` as well for `humburg.phar`.

Allow to be run with phpdbg

---

features/bootstrap/FilesystemContext.php
features/newprojects/developer_sees_mutant_skipped_test_if_no_tests_result.feature
features/newprojects/developer_sees_no_mutation_testing_occur_if_no_sourcecode.feature

See #169, #189 and #234
Need to check on Windows to see if these fail there. Work as expected on Ubuntu.

Add behat features checking empty project states

---

src/Adapter/Phpunit.php
src/Command/Configure.php
src/Command/Humbug.php
src/Command/SelfUpdate.php
src/Container.php
src/Mutator/Arithmetic/Addition.php
src/ProcessRunner.php
src/Renderer/Text.php
src/TestSuite/Mutant/IncrementalCache.php
src/TestSuite/Mutant/Runner.php

Adds additional PSR-2 fixes from implementing #240. PHP CodeSniffer is stricter than StyleCI, but usually for fairly inconsequential things. This just cleans those up so using `composer cs-check` doesn't explode.

Basic PSR-2 error fixes from running phpcbf

---

README.md
features/bootstrap/FeatureContext.php
features/running/developer_sees_mutant_error_result.feature
features/version.feature
src/Mutable.php

According to @MarkRedeman, only methods should be mutated right now and
function support is pending. `$inMethod` was set to `true` for functions
as well, because it didn't check whether it's inside a class.

Mutate only methods, no functions

---

bootstrap.php
src/Command/Humbug.php

Move xdebug/phpdbg warning to where actually needed - fixes #203

---

.gitignore
composer.json
vendor-bin/phpmnd/composer.json

This is a simple tool for tracking numbers which should be defined via constants (i.e. magic numbers). Something not actually covered by Scrutinizer/PHPMD.

Include phpmnd (PHP Magic Number Detector) as a dev require

---

README.md
src/Command/Humbug.php

I've added the option 'path' for full path files to mutate. Files from path with be intersected with the files found by Symfony/Finder using config directory and 'file' option. 
Ex:
Config:
```json
{
"timeout": 10,
"source": {
"directories": [
"src"
],
"excludes": [
"vendor",
"tests"
]
},
"logs": {
"json": "humbug/humbuglog.json"
}
}
```
Command: 
```
humbug --file=Service.php \
--file=GetData.php \
--path=src/Data/Request/GetData.php \
--path=src/Data/Infrastructure/Persistence/DAL/GetData.php \
--path=src/Data/Response/GetData.php
```
Files found by Symfony/Finder:
```
src/Data/GetData.php
src/Data/Request/GetData.php
src/Data/Infrastructure/Persistence/DAL/GetData.php
src/Data/Service.php
src/Service.php
```
Running the command with the config above the mutated files will be:
``` …
```

Add files filter

---

composer.json

It may help users to detect problems during the Humbug install.

Add the list of required PHP extensions in composer.json
